<a href="https://colab.research.google.com/github/Faareh-Ahmed/Biomass-Prediction-from-3D-Point-Cloud/blob/main/pointcloud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os

# Base directory inside content/sample_data
base_dir = '/content/sample_data/TextFilesData/20190828'

# Create folders from Tony e-w_20190828_001 to Tony e-w_20190828_013
for i in range(1, 14):
    folder_name = f'Tonye-w_20190828_{str(i).zfill(3)}'
    folder_path = os.path.join(base_dir, folder_name)
    os.makedirs(folder_path, exist_ok=True)

print("Folders created successfully!")

Folders created successfully!

In [2]:
base_dir_2 = '/content/sample_data/TextFilesData/20191002'
# Create folders from Tony e-w_20191002_001 to Tony e-w_20191002_013
for i in range(1, 14):
    folder_name = f'Tonye-w_20191002_{str(i).zfill(3)}'
    folder_path = os.path.join(base_dir_2, folder_name)
    os.makedirs(folder_path, exist_ok=True)

print("Folders created successfully!")

Folders created successfully!

In [37]:
import os

# Base directory where the folders are located
base_dir = '/content/sample_data/TextFilesData/20190828'

# Iterate over all the subdirectories in the base directory
for folder_name in os.listdir(base_dir):
    # Check if the folder name contains the incorrect 'Tonye-w'
    if 'Tony-e-w' in folder_name:
        # Replace 'Tonye-w' with 'Tony-e-w' in the folder name
        corrected_folder_name = folder_name.replace('Tony-e-w', 'Tonye-w')

        # Construct the full paths for the old and new folder names
        old_folder_path = os.path.join(base_dir, folder_name)
        new_folder_path = os.path.join(base_dir, corrected_folder_name)

        # Rename the folder
        os.rename(old_folder_path, new_folder_path)
        print(f"Renamed: {old_folder_path} -> {new_folder_path}")

print("Folder renaming completed!")

Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_007 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_007
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_012 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_012
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_002 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_002
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_003 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_003
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_005 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_005
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_009 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_009
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_008 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_008
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_011 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_011
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_006 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_006
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_013 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_013
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_010 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_010
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_004 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_004
Renamed: /content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_001 -> /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_001
Folder renaming completed!

In [43]:
import os

# Base directory where the folders are located
base_dir = '/content/sample_data/TextFilesData/20191002'

# Iterate over all the subdirectories in the base directory
for folder_name in os.listdir(base_dir):
    # Check if the folder name contains the incorrect 'Tonye-w'
    if 'Tony-e-w' in folder_name:
        # Replace 'Tonye-w' with 'Tony-e-w' in the folder name
        corrected_folder_name = folder_name.replace('Tony-e-w', 'Tonye-w')

        # Construct the full paths for the old and new folder names
        old_folder_path = os.path.join(base_dir, folder_name)
        new_folder_path = os.path.join(base_dir, corrected_folder_name)

        # Rename the folder
        os.rename(old_folder_path, new_folder_path)
        print(f"Renamed: {old_folder_path} -> {new_folder_path}")

print("Folder renaming completed!")

Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_007 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_007
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_003 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_003
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_006 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_006
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_005 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_005
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_010 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_010
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_009 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_009
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_004 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_004
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_013 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_013
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_012 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_012
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_001 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_001
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_011 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_011
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_002 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_002
Renamed: /content/sample_data/TextFilesData/20191002/Tony-e-w_20191002_008 -> /content/sample_data/TextFilesData/20191002/Tonye-w_20191002_008
Folder renaming completed!

In [3]:
cd /content/sample_data/TextFilesData

/content/sample_data/TextFilesData

In [3]:
import pandas as pd

# Path to the train_list.txt file
train_list_path = '/content/sample_data/TextFilesData/train_list.txt'

# Read the file into a DataFrame
df = pd.read_csv(train_list_path, delim_whitespace=True, header=None)

# Display the DataFrame
print(df)

                  0                               1        2   3   4  5
0    /20190828/Tony    e-w_20190828_001/1-5-1-b.pcd   380.60   3   1  3
1    /20190828/Tony    e-w_20190828_001/1-7-1-b.pcd   309.27   4   1  3
2    /20190828/Tony    e-w_20190828_001/1-9-1-b.pcd   303.53   5   1  3
3    /20190828/Tony   e-w_20190828_001/1-11-1-b.pcd   410.57   6   1  3
4    /20190828/Tony   e-w_20190828_001/1-13-1-b.pcd   204.15   7   1  3
..              ...                             ...      ...  ..  .. ..
199  /20191002/Tony  e-w_20191002_013/13-11-1-b.pcd  1177.20   6  13  4
200  /20191002/Tony  e-w_20191002_013/13-13-1-b.pcd   941.60   7  13  4
201  /20191002/Tony  e-w_20191002_013/13-14-1-b.pcd   568.00   8  13  4
202  /20191002/Tony  e-w_20191002_013/13-17-1-b.pcd   853.00  11  13  4
203  /20191002/Tony  e-w_20191002_013/13-18-1-b.pcd   686.00  12  13  4

[204 rows x 6 columns]

<ipython-input-3-853a622e4250>:7: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(train_list_path, delim_whitespace=True, header=None)

In [6]:
df.head()

                0                              1       2  3  4  5
0  /20190828/Tony   e-w_20190828_001/1-5-1-b.pcd  380.60  3  1  3
1  /20190828/Tony   e-w_20190828_001/1-7-1-b.pcd  309.27  4  1  3
2  /20190828/Tony   e-w_20190828_001/1-9-1-b.pcd  303.53  5  1  3
3  /20190828/Tony  e-w_20190828_001/1-11-1-b.pcd  410.57  6  1  3
4  /20190828/Tony  e-w_20190828_001/1-13-1-b.pcd  204.15  7  1  3

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       204 non-null    object
 1   1       204 non-null    object
 2   2       204 non-null    float64
 3   3       204 non-null    int64
 4   4       204 non-null    int64
 5   5       204 non-null    int64
dtypes: float64(1), int64(3), object(2)
memory usage: 9.7+ KB

In [4]:
df[0]=df[0]+df[1]
df[0]

0        /20190828/Tonye-w_20190828_001/1-5-1-b.pcd
1        /20190828/Tonye-w_20190828_001/1-7-1-b.pcd
2        /20190828/Tonye-w_20190828_001/1-9-1-b.pcd
3       /20190828/Tonye-w_20190828_001/1-11-1-b.pcd
4       /20190828/Tonye-w_20190828_001/1-13-1-b.pcd
                           ...
199    /20191002/Tonye-w_20191002_013/13-11-1-b.pcd
200    /20191002/Tonye-w_20191002_013/13-13-1-b.pcd
201    /20191002/Tonye-w_20191002_013/13-14-1-b.pcd
202    /20191002/Tonye-w_20191002_013/13-17-1-b.pcd
203    /20191002/Tonye-w_20191002_013/13-18-1-b.pcd
Name: 0, Length: 204, dtype: object

In [5]:
df[0] = df[0].str.replace('.pcd', '.txt')
df[0]

0        /20190828/Tonye-w_20190828_001/1-5-1-b.txt
1        /20190828/Tonye-w_20190828_001/1-7-1-b.txt
2        /20190828/Tonye-w_20190828_001/1-9-1-b.txt
3       /20190828/Tonye-w_20190828_001/1-11-1-b.txt
4       /20190828/Tonye-w_20190828_001/1-13-1-b.txt
                           ...
199    /20191002/Tonye-w_20191002_013/13-11-1-b.txt
200    /20191002/Tonye-w_20191002_013/13-13-1-b.txt
201    /20191002/Tonye-w_20191002_013/13-14-1-b.txt
202    /20191002/Tonye-w_20191002_013/13-17-1-b.txt
203    /20191002/Tonye-w_20191002_013/13-18-1-b.txt
Name: 0, Length: 204, dtype: object

In [6]:
df = df.drop(columns=[1])

In [12]:
df.head()

                                             0       2  3  4  5
0   /20190828/Tonye-w_20190828_001/1-5-1-b.txt  380.60  3  1  3
1   /20190828/Tonye-w_20190828_001/1-7-1-b.txt  309.27  4  1  3
2   /20190828/Tonye-w_20190828_001/1-9-1-b.txt  303.53  5  1  3
3  /20190828/Tonye-w_20190828_001/1-11-1-b.txt  410.57  6  1  3
4  /20190828/Tonye-w_20190828_001/1-13-1-b.txt  204.15  7  1  3

In [7]:
pip install torch torchvision torchaudio torch-geometric

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.4.1+cu121)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.19.1+cu121)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.10/dist-packages (2.4.1+cu121)
Requirement already satisfied: torch-geometric in /usr/local/lib/python3.10/dist-packages (2.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2024.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (10.4.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.10.8)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (3.1.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from torch-geometric) (4.66.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (2.4.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (1.13.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->torch-geometric) (4.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->torch-geometric) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)

In [8]:
pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
df

                                                0        2   3   4  5
0      /20190828/Tonye-w_20190828_001/1-5-1-b.txt   380.60   3   1  3
1      /20190828/Tonye-w_20190828_001/1-7-1-b.txt   309.27   4   1  3
2      /20190828/Tonye-w_20190828_001/1-9-1-b.txt   303.53   5   1  3
3     /20190828/Tonye-w_20190828_001/1-11-1-b.txt   410.57   6   1  3
4     /20190828/Tonye-w_20190828_001/1-13-1-b.txt   204.15   7   1  3
..                                            ...      ...  ..  .. ..
199  /20191002/Tonye-w_20191002_013/13-11-1-b.txt  1177.20   6  13  4
200  /20191002/Tonye-w_20191002_013/13-13-1-b.txt   941.60   7  13  4
201  /20191002/Tonye-w_20191002_013/13-14-1-b.txt   568.00   8  13  4
202  /20191002/Tonye-w_20191002_013/13-17-1-b.txt   853.00  11  13  4
203  /20191002/Tonye-w_20191002_013/13-18-1-b.txt   686.00  12  13  4

[204 rows x 5 columns]

In [25]:
/content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_001/1-5-1-b.txt

'/content/sample_data/TextFilesData'

In [30]:
/content/sample_data/TextFilesData/20190828/Tony-e-w_20190828_001/1-5-1-b.txt

'/content/sample_data/TextFilesData'

In [10]:
base_dir = '/content/sample_data/TextFilesData'

for _, row in df.iterrows():
    # Construct the full file path
    full_path = os.path.join(base_dir, row[0].lstrip('/'))  # Remove leading slash using lstrip
    print(full_path)  # Print the full path to check if it's correct
    # Check if the file exists
    if os.path.exists(full_path):
        print(f"File exists: {full_path}")
    else:
        print(f"File not found: {full_path}")
    break  # Just check for the first file

/content/sample_data/TextFilesData/20190828/Tonye-w_20190828_001/1-5-1-b.txt
File exists: /content/sample_data/TextFilesData/20190828/Tonye-w_20190828_001/1-5-1-b.txt

In [11]:

# Base directory
base_dir = '/content/sample_data/TextFilesData'

# Example to read point cloud data
def load_point_cloud(file_path):
    # Load the point cloud data from the .txt file
    point_cloud = pd.read_csv(file_path, delimiter=' ', header=None)  # Adjust delimiter based on your file format
    return point_cloud.values  # Convert to NumPy array or leave as DataFrame based on your needs

# Load point clouds and biomass values
point_clouds = []
biomass_values = []

for _, row in df.iterrows():
    # Construct the full file path
    full_path = base_dir + row[0]  # row[0] contains the relative file path
    point_cloud = load_point_cloud(full_path)  # Load point cloud data

    point_clouds.append(point_cloud)
    biomass_values.append(row[2])  # Assuming biomass value is in the second column

# Convert to NumPy arrays
point_clouds = np.array(point_clouds, dtype=object)  # Use dtype=object for an array of arrays
biomass_values = np.array(biomass_values)

# Now point_clouds and biomass_values are ready for your next steps

In [47]:
point_clouds.shape

(204,)

In [48]:
biomass_values.shape

(204,)

In [53]:
biomass_values

array([ 380.6 ,  309.27,  303.53,  410.57,  204.15,  202.87,  394.2 ,
        196.74,  390.9 ,  383.73,  360.19,  284.64,  274.64,  293.43,
        277.65,  276.52,  424.64,  467.7 ,  506.07,  420.09,  251.99,
        197.72,  212.23,  307.98,  432.09,  419.71,  471.09,  444.38,
        241.04,  232.97,  209.  ,  222.45,  399.36,  469.57,  444.04,
        320.57,  236.81,  238.33,  203.98,  264.81,  344.31,  309.11,
        314.71,  274.27,  275.28,  216.46,  221.45,  149.78,  328.19,
        359.7 ,  356.36,  461.72,  220.67,  310.06,  335.34,  224.68,
        336.63,  376.51,  410.06,  316.62,  239.11,  159.71,  206.3 ,
        240.47,  287.12,  440.63,  459.9 ,  400.18,  207.98,  287.16,
        156.18,  238.85,  443.54,  336.57,  351.74,  434.03,  246.81,
        279.31,  220.98,  236.32,  346.41,  440.13,  398.12,  338.81,
        219.25,  224.93,  350.86,  299.12,  283.5 ,  336.64,  357.87,
        316.33,  164.13,  166.61,  171.59,  178.26,  383.17,  322.85,
        335.98,  362.78,  274.87,  274.19,  258.7 ,  151.4 ,  982.4 ,
       1057.4 ,  931.4 , 1265.6 ,  636.8 ,  810.8 ,  894.8 ,  799.6 ,
       1008.8 , 1126.8 ,  995.  ,  955.  , 1085.  , 1034.6 ,  941.2 ,
       1159.8 , 1163.4 , 1171.8 , 1341.8 , 1171.4 ,  644.8 ,  731.  ,
       1088.2 ,  819.2 , 1098.4 , 1239.  , 1225.2 , 1178.4 , 1095.2 ,
        922.4 ,  778.4 ,  955.8 , 1094.  , 1093.  , 1281.8 , 1086.8 ,
       1062.2 , 1033.6 , 1129.4 , 1080.6 , 1013.4 ,  945.  ,  891.4 ,
        635.2 , 1114.  , 1041.2 , 1173.6 , 1274.  ,  768.8 ,  936.4 ,
       1146.6 ,  945.  , 1072.4 , 1233.  , 1175.6 , 1099.  ,  999.2 ,
        842.8 , 1048.6 , 1169.6 , 1096.8 , 1206.2 , 1317.6 , 1119.6 ,
        636.8 ,  835.2 ,  722.2 ,  919.8 , 1179.6 , 1126.  , 1041.8 ,
       1240.8 , 1015.4 ,  886.6 ,  805.4 , 1106.6 , 1129.  , 1204.4 ,
       1140.4 , 1002.2 ,  797.  ,  963.2 ,  841.8 , 1029.2 , 1019.  ,
       1021.8 , 1102.2 , 1093.4 ,  902.2 ,  719.2 ,  799.6 ,  941.4 ,
       1215.2 , 1106.2 , 1056.2 , 1177.2 ,  941.6 ,  568.  ,  853.  ,
        686.  ])

In [12]:
import numpy as np
from scipy.spatial import Delaunay

# Function to create a 3D graph from the point cloud using Delaunay triangulation
def create_3d_graph(points):
    # Count NaN rows before filtering
    nan_count = np.isnan(points).any(axis=1).sum()

    # Filter out any rows with NaN values
    valid_points = points[~np.isnan(points).any(axis=1), :3]  # Keep only X, Y, Z coordinates

    # Print the number of NaN rows deleted
    print(f"Deleted {nan_count} rows containing NaN values.")

    # Check if there are enough points left for triangulation (at least 4 points in 3D)
    if valid_points.shape[0] < 4:
        raise ValueError("Not enough valid points for Delaunay triangulation")

    tri = Delaunay(valid_points)  # Create the Delaunay triangulation in 3D
    edges = set()  # Store edges as a set to avoid duplicates
    for simplex in tri.simplices:
        for i in range(3):
            # Create edges between the points of each triangle
            edges.add((simplex[i], simplex[(i + 1) % 3]))
    return edges

# List to hold graphs for each point cloud
graphs = []

for point_cloud in point_clouds:
    # Skip the header row if necessary (i.e., ['//X', 'Y', 'Z', 'intensity'])
    if isinstance(point_cloud[0][0], str):
        point_cloud = point_cloud[1:]  # Remove the header row

    # Convert point cloud to NumPy array for processing
    point_cloud_array = np.array(point_cloud, dtype=float)  # Ensure it is float

    # Create graph for current point cloud in 3D, handling NaN values
    try:
        edges = create_3d_graph(point_cloud_array)  # Create the graph
        graphs.append((point_cloud_array, edges))  # Store points and their edges
    except ValueError as e:
        print(f"Skipping point cloud due to error: {e}")

# Now, 'graphs' contains a list of (point_cloud, edges) tuples, considering 3D space and NaN handling.

Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 0 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 0 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.
Deleted 1 rows containing NaN values.

In [13]:
import torch
from torch_geometric.nn import MessagePassing

class GNNModel(MessagePassing):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GNNModel, self).__init__(aggr='mean')  # "Mean" aggregation.
        self.lin1 = torch.nn.Linear(in_channels, hidden_channels)
        self.lin2 = torch.nn.Linear(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        x = self.lin1(x)
        x = torch.relu(x)
        x = self.propagate(edge_index, x=x)
        x = self.lin2(x)
        return x

    def message(self, x_j):
        return x_j

In [14]:
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader  # Update the import

data_list = []
for points, edges in graphs:
    x = torch.tensor(points, dtype=torch.float)  # Node features
    edge_index = torch.tensor(list(edges), dtype=torch.long).t().contiguous()  # Edge list
    data = Data(x=x, edge_index=edge_index)
    data_list.append(data)

train_loader = DataLoader(data_list, batch_size=32, shuffle=True)  # Adjust batch size as needed